"""R5.2: desk CSS lives in css/*.css; app.css is generated."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSS_DIR = ROOT / "src/gnom_hub/ui/static/css"
APP = (ROOT / "src/gnom_hub/ui/static/app.css").read_text(encoding="utf-8")
EXPECTED = [
    "00-core.css",
    "01-agents.css",
    "02-boxes.css",
    "03-chat.css",
    "04-jobs.css",
    "05-system.css",
    "06-workspace.css",
    "07-rest.css",
]
BANNER = (
    "/* Generated by scripts/build_ui_css.py — edit css/*.css, not this file. */\n"
    '@import url("tokens.css");\n'
    "\n"
)


def test_area_files_exist_in_cascade_order():
    names = [p.name for p in sorted(CSS_DIR.glob("*.css"))]
    assert names == EXPECTED


def test_app_css_is_generated_concat_of_area_files():
    body = "".join((CSS_DIR / name).read_text(encoding="utf-8") for name in EXPECTED)
    assert APP == BANNER + body
    assert APP.startswith(BANNER)
    assert '@import url("tokens.css")' in APP
    assert "edit css/*.css, not this file" in APP.splitlines()[0]


def test_build_ui_css_check_matches_app_css():
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts/build_ui_css.py"), "--check"],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr


def test_area_files_do_not_repeat_token_palette_or_import():
    for name in EXPECTED:
        text = (CSS_DIR / name).read_text(encoding="utf-8")
        assert "@import" not in text
        assert "--btn-h: 20px" not in text
        assert "--c-flex: #f0c000" not in text


def test_built_app_keeps_r4_selectors():
    for sel in (
        ".boxes",
        ".box2-stack",
        ".chat-mod",
        ".agent-cards",
        ".workspace-panel",
        ".toast-host",
        ".tools-run-history",
        ".box2-reply-tab",
        ".box3-worker-tab",
        ".box3-keep-bar",
        ".btn-mic",
        ".god-badge",
        ".help-tab",
    ):
        assert sel in APP, f"missing {sel} in generated app.css"


def test_area_file_ownership():
    assert ".top-bar" in (CSS_DIR / "00-core.css").read_text(encoding="utf-8")
    assert ".agent-cards" in (CSS_DIR / "01-agents.css").read_text(encoding="utf-8")
    assert ".boxes" in (CSS_DIR / "02-boxes.css").read_text(encoding="utf-8")
    assert ".chat-mod" in (CSS_DIR / "03-chat.css").read_text(encoding="utf-8")
    assert ".box-3" in (CSS_DIR / "04-jobs.css").read_text(encoding="utf-8")
    assert ".modal" in (CSS_DIR / "05-system.css").read_text(encoding="utf-8")
    assert ".workspace-panel" in (CSS_DIR / "06-workspace.css").read_text(encoding="utf-8")
    assert ".toast-host" in (CSS_DIR / "07-rest.css").read_text(encoding="utf-8")
    assert ".tools-run-history" in (CSS_DIR / "07-rest.css").read_text(encoding="utf-8")
