"""Key.txt → private .env. Simple KEY=value parsing, no extra deps.

Preferred location: User/Key.txt (with User/user.db).
Legacy fallback: repo-root Key.txt.
"""

from __future__ import annotations

import os
import re
import shutil
from pathlib import Path

from gnom_hub.config.paths import project_root, user_dir

# Common short names → canonical env names
_ALIASES: dict[str, str] = {
    "deepseek": "DEEPSEEK_API_KEY",
    "deepseek_key": "DEEPSEEK_API_KEY",
    "deepseek_api_key": "DEEPSEEK_API_KEY",
    # System agents (brainstorm / memory / flex / coordinator) + global default
    "system": "DEEPSEEK_API_KEY",
    "system_key": "DEEPSEEK_API_KEY",
    "system_api_key": "DEEPSEEK_API_KEY",
    # All workers (worker1–4)
    "worker": "WORKER_API_KEY",
    "worker_key": "WORKER_API_KEY",
    "worker_api_key": "WORKER_API_KEY",
    "workers": "WORKER_API_KEY",
    "deepseek_worker": "WORKER_API_KEY",
    # Default model id for DeepSeek (e.g. deepseek-v4-flash)
    "model": "DEEPSEEK_MODEL",
    "deepseek_model": "DEEPSEEK_MODEL",
    "default_model": "DEEPSEEK_MODEL",
}

_LINE_RE = re.compile(r"^\s*(?:export\s+)?([A-Za-z_][\w]*)\s*[=:]\s*(.+?)\s*$")


def _normalize_key(name: str) -> str:
    raw = name.strip()
    lower = raw.lower()
    if lower in _ALIASES:
        return _ALIASES[lower]
    return raw.upper()


def _strip_value(value: str) -> str:
    v = value.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
        v = v[1:-1]
    return v.strip()


def parse_key_file(text: str) -> dict[str, str]:
    """Parse Key.txt / .env style content into a dict."""
    out: dict[str, str] = {}
    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        m = _LINE_RE.match(line)
        if not m:
            continue
        key = _normalize_key(m.group(1))
        val = _strip_value(m.group(2))
        if val:
            out[key] = val
    return out


def atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


def env_text_from_keys(keys: dict[str, str]) -> str:
    lines = [
        "# Generated by Gnom-Hub from User/Key.txt – do not commit.",
        "",
    ]
    for k in sorted(keys):
        lines.append(f"{k}={keys[k]}")
    lines.append("")
    return "\n".join(lines)


def resolve_key_txt_path(
    root: Path | None = None,
    *,
    key_filename: str = "Key.txt",
) -> Path | None:
    """
    Prefer User/Key.txt; fall back to repo-root Key.txt (legacy).

    One-shot: if only root Key.txt exists, copy into User/ so the layout stays clean.
    """
    base = Path(root) if root is not None else project_root()
    preferred = user_dir(base) / key_filename
    legacy = base / key_filename
    if preferred.is_file():
        return preferred
    if legacy.is_file():
        # Seed User/ from root once (do not delete root — operator may still have it)
        try:
            preferred.parent.mkdir(parents=True, exist_ok=True)
            if not preferred.exists():
                shutil.copy2(legacy, preferred)
            if preferred.is_file():
                return preferred
        except OSError:
            return legacy
        return legacy
    return None


def ensure_env_from_key_txt(
    root: Path | None = None,
    *,
    key_filename: str = "Key.txt",
    env_filename: str = ".env",
    force: bool = False,
) -> Path | None:
    """
    If User/Key.txt (or legacy root Key.txt) exists, write private .env (atomic).

    - Prefer User/Key.txt as source of truth
    - If .env missing → write from Key.txt
    - If force=True → overwrite .env from Key.txt
    - If Key.txt missing → no-op, return None
    Returns path to .env when written or already present after Key.txt merge.
    """
    base = Path(root) if root is not None else project_root()
    key_path = resolve_key_txt_path(base, key_filename=key_filename)
    env_path = base / env_filename

    if key_path is None or not key_path.is_file():
        return env_path if env_path.is_file() else None

    from_key = parse_key_file(key_path.read_text(encoding="utf-8"))
    if not from_key:
        return env_path if env_path.is_file() else None

    # Hub keys always win from Key.txt so edits take effect without force=
    HUB_OWNED = {
        "DEEPSEEK_API_KEY",
        "WORKER_API_KEY",
        "DEEPSEEK_MODEL",
        "TELEGRAM_BOT_TOKEN",
    }
    if env_path.is_file() and not force:
        existing = parse_key_file(env_path.read_text(encoding="utf-8"))
        merged = dict(existing)
        for k, v in from_key.items():
            if k in HUB_OWNED or k not in merged:
                merged[k] = v
        if merged != existing:
            atomic_write_text(env_path, env_text_from_keys(merged))
        return env_path

    atomic_write_text(env_path, env_text_from_keys(from_key))
    return env_path


def load_keys(
    root: Path | None = None,
    *,
    env_filename: str = ".env",
    apply_environ: bool = True,
) -> dict[str, str]:
    """
    Load keys from .env (and process env).

    Call ensure_env_from_key_txt() first if you want Key.txt → .env migration.
    """
    base = root or project_root()
    env_path = base / env_filename
    keys: dict[str, str] = {}

    if env_path.is_file():
        keys.update(parse_key_file(env_path.read_text(encoding="utf-8")))

    # Process environment wins for already-exported secrets (CI, shell)
    for k, v in os.environ.items():
        if (k.endswith("_API_KEY") or k in ("DEEPSEEK_API_KEY",)) and v.strip():
            keys[k] = v.strip()

    if apply_environ:
        for k, v in keys.items():
            os.environ.setdefault(k, v)

    return keys


def has_deepseek_key(keys: dict[str, str] | None = None) -> bool:
    k = keys if keys is not None else load_keys()
    return bool(k.get("DEEPSEEK_API_KEY", "").strip())
