#!/usr/bin/env python3
"""Concatenate ui/static/css/*.css → ui/static/app.css (order by filename).

Edit css/*.css, then run this script. Do not edit app.css by hand.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSS_DIR = ROOT / "src" / "gnom_hub" / "ui" / "static" / "css"
OUT = ROOT / "src" / "gnom_hub" / "ui" / "static" / "app.css"
BANNER = (
    "/* Generated by scripts/build_ui_css.py — edit css/*.css, not this file. */\n"
    '@import url("tokens.css");\n'
    "\n"
)


def built_text() -> str:
    files = sorted(CSS_DIR.glob("*.css"))
    if not files:
        raise SystemExit(f"no css parts in {CSS_DIR}")
    body = "".join(p.read_text(encoding="utf-8") for p in files)
    if body.startswith("\ufeff"):
        body = body.lstrip("\ufeff")
    return BANNER + body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if app.css does not match a fresh build",
    )
    args = parser.parse_args()
    text = built_text()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("app.css is stale — run: python3 scripts/build_ui_css.py", file=sys.stderr)
            return 1
        print(f"ok {OUT.relative_to(ROOT)} matches {len(sorted(CSS_DIR.glob('*.css')))} css parts")
        return 0
    OUT.write_text(text, encoding="utf-8")
    files = sorted(CSS_DIR.glob("*.css"))
    print(f"built {OUT.relative_to(ROOT)} from {len(files)} parts ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
