#!/usr/bin/env python3
"""Build searchable docs index + catalog JSON (stdlib only).

Usage:
  python scripts/build_docs_index.py              # write INDEX.md + catalog
  python scripts/build_docs_index.py --check       # exit 1 if drift
  python scripts/build_docs_index.py --search "skill embeddings"
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
INDEX_MD = DOCS / "INDEX.md"
CATALOG = DOCS / "generated" / "docs_catalog.json"

# filename stem → topic bucket (search + INDEX grouping)
TOPIC_RULES: list[tuple[str, re.Pattern[str]]] = [
    ("Install & run", re.compile(r"INSTALL|KEYS_AND|STABILITY|UI_QUALITY|PYTHON_CACHE", re.I)),
    (
        "Architecture & agents",
        re.compile(
            r"ARCHITECTURE|HUB_|ORCHESTRATION|AGENTS_DEFINITION|LAYERS|CODE_ANALYSIS|WORKFLOWS|MCP_",
            re.I,
        ),
    ),
    ("Skills & plugins", re.compile(r"SKILL|PLUGIN|TOOLS_PORT|WORKER_", re.I)),
    ("Memory & vectors", re.compile(r"VECTOR|EMBED", re.I)),
    ("Quality & tests", re.compile(r"TEST|MUTMUT|DOD|ERROR|BASIC_USER|REAL_USER|UI_ERROR", re.I)),
    (
        "Product & history",
        re.compile(r"SCOPE|ROADMAP|V4_|V1_|PRE_PLAN|MERGE|CHANGELOG|GITHUB_HOLDER|PLAN_VS", re.I),
    ),
    ("Frontend lint", re.compile(r"ESLINT|MERMAID", re.I)),
    ("Other", re.compile(r".*")),
]

STOP = frozenset(
    "the a an and or for with from this that into your are was were be been "
    "ist und der die das ein eine mit von zu im in of to on als bei den dem "
    "not no yes only when how what docs doc see also etc md".split()
)
_WORD = re.compile(r"[A-Za-zÄÖÜäöüß0-9_]{3,}")


def _title(text: str, stem: str) -> str:
    for line in text.splitlines()[:40]:
        s = line.strip()
        if s.startswith("# "):
            return s[2:].strip()
    return stem.replace("_", " ")


def _keywords(text: str, stem: str, limit: int = 14) -> list[str]:
    head = "\n".join(text.splitlines()[:80])
    counts: dict[str, int] = {}
    for w in _WORD.findall(head + " " + stem.replace("_", " ")):
        wl = w.lower()
        if wl in STOP or wl.isdigit():
            continue
        counts[wl] = counts.get(wl, 0) + 1
    # boost stem tokens
    for part in stem.lower().split("_"):
        if part and part not in STOP:
            counts[part] = counts.get(part, 0) + 5
    ranked = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
    return [k for k, _ in ranked[:limit]]


def _topic(stem: str) -> str:
    for name, pat in TOPIC_RULES:
        if pat.search(stem):
            return name
    return "Other"


def collect() -> list[dict]:
    rows: list[dict] = []
    for path in sorted(DOCS.glob("*.md")):
        if path.name == "INDEX.md":
            continue
        raw = path.read_text(encoding="utf-8", errors="replace")
        stem = path.stem
        rows.append(
            {
                "file": path.name,
                "path": f"docs/{path.name}",
                "title": _title(raw, stem),
                "topic": _topic(stem),
                "keywords": _keywords(raw, stem),
                "chars": len(raw),
                "lines": raw.count("\n") + 1,
            }
        )
    return rows


def render_index(rows: list[dict], version: str = "3.10.1") -> str:
    by: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by[r["topic"]].append(r)
    order = [n for n, _ in TOPIC_RULES if n in by]
    for k in sorted(by):
        if k not in order:
            order.append(k)

    lines = [
        "# Documentation index (searchable)",
        "",
        f"<!-- AUTO-GENERATED by scripts/build_docs_index.py — do not edit by hand -->",
        "",
        f"**Start:** [README.md](../README.md) (EN) · [README_DE.md](../README_DE.md) (DE)  ",
        f"**Version:** {version} · [CHANGELOG_3.10.md](CHANGELOG_3.10.md)  ",
        f"**Catalog JSON:** [generated/docs_catalog.json](generated/docs_catalog.json)  ",
        f"**Search:** `python scripts/build_docs_index.py --search \"query\"` · API `GET /api/docs/search?q=`",
        "",
        "Use this page as a **keyword map**. Ctrl/Cmd-F in the browser or IDE.",
        "",
        "---",
        "",
        "## By topic",
        "",
    ]
    for topic in order:
        lines.append(f"### {topic}")
        lines.append("| Doc | Keywords |")
        lines.append("|-----|----------|")
        for r in sorted(by[topic], key=lambda x: x["file"]):
            kw = ", ".join(r["keywords"][:10])
            lines.append(f"| [{r['file']}]({r['file']}) | {kw} |")
        lines.append("")

    lines += [
        "### Root meta",
        "| Doc | Keywords |",
        "|-----|----------|",
        "| [../AGENTS.md](../AGENTS.md) | coding rules, freeze, push gate |",
        "| [../README.md](../README.md) | English product README |",
        "| [../README_DE.md](../README_DE.md) | German product README |",
        "",
        "---",
        "",
        "## A–Z file list",
        "",
    ]
    for r in sorted(rows, key=lambda x: x["file"].lower()):
        lines.append(f"- [{r['file']}]({r['file']}) — {r['title']}")
    lines.append("")
    return "\n".join(lines)


def search(rows: list[dict], query: str, limit: int = 12) -> list[dict]:
    q = [t for t in re.findall(r"[a-z0-9äöüß_]{2,}", query.lower()) if t not in STOP]
    if not q:
        return []
    scored: list[tuple[int, dict]] = []
    for r in rows:
        blob = " ".join(
            [
                r["file"].lower(),
                r["title"].lower(),
                r["topic"].lower(),
                " ".join(r["keywords"]),
            ]
        )
        # also skim file body lightly
        path = ROOT / r["path"]
        try:
            body = path.read_text(encoding="utf-8", errors="replace")[:4000].lower()
        except OSError:
            body = ""
        score = 0
        for t in q:
            if t in r["file"].lower():
                score += 8
            if t in r["title"].lower():
                score += 6
            if t in r["keywords"]:
                score += 5
            if t in blob:
                score += 2
            if t in body:
                score += 1
        if score:
            scored.append((score, r))
    scored.sort(key=lambda x: (-x[0], x[1]["file"]))
    out = []
    for sc, r in scored[:limit]:
        hit = dict(r)
        hit["score"] = sc
        out.append(hit)
    return out


def write_outputs(rows: list[dict]) -> None:
    CATALOG.parent.mkdir(parents=True, exist_ok=True)
    ver = "3.10.1"
    try:
        init = (ROOT / "src" / "gnom_hub" / "__init__.py").read_text(encoding="utf-8")
        m = re.search(r'__version__\s*=\s*["\']([^"\']+)', init)
        if m:
            ver = m.group(1)
    except OSError:
        pass
    INDEX_MD.write_text(render_index(rows, version=ver), encoding="utf-8")
    CATALOG.write_text(
        json.dumps({"version": ver, "count": len(rows), "docs": rows}, indent=2) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if INDEX/catalog drift")
    ap.add_argument("--search", type=str, default="", help="search query")
    ap.add_argument("--limit", type=int, default=12)
    args = ap.parse_args()
    rows = collect()

    ver = "3.10.1"
    try:
        init = (ROOT / "src" / "gnom_hub" / "__init__.py").read_text(encoding="utf-8")
        m = re.search(r'__version__\s*=\s*["\']([^"\']+)', init)
        if m:
            ver = m.group(1)
    except OSError:
        pass

    if args.search.strip():
        hits = search(rows, args.search, limit=args.limit)
        for h in hits:
            print(f"{h['score']:3d}  {h['path']}  —  {h['title']}")
            print(f"     keywords: {', '.join(h['keywords'][:8])}")
        if not hits:
            print("(no hits)")
            return 1
        return 0

    new_idx = render_index(rows, version=ver)
    new_cat = json.dumps({"version": ver, "count": len(rows), "docs": rows}, indent=2) + "\n"

    if args.check:
        old_idx = INDEX_MD.read_text(encoding="utf-8") if INDEX_MD.is_file() else ""
        old_cat = CATALOG.read_text(encoding="utf-8") if CATALOG.is_file() else ""
        if old_idx != new_idx or old_cat != new_cat:
            print("docs index/catalog out of date — run:", file=sys.stderr)
            print("  python scripts/build_docs_index.py", file=sys.stderr)
            print("  git add docs/INDEX.md docs/generated/docs_catalog.json", file=sys.stderr)
            return 1
        print(f"docs index OK ({len(rows)} docs)")
        return 0

    CATALOG.parent.mkdir(parents=True, exist_ok=True)
    INDEX_MD.write_text(new_idx, encoding="utf-8")
    CATALOG.write_text(new_cat, encoding="utf-8")
    print(f"wrote {INDEX_MD.relative_to(ROOT)} ({len(rows)} docs)")
    print(f"wrote {CATALOG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
